version: '3'

services:
  api:
    build:
      context: .devcontainer
      dockerfile: Dockerfile.deploy
    restart: always
    init: true
    ports:
      - "${LOCAL_IP:-127.0.0.1}:${API_PORT:-8000}:8000"
