services:
  api:
    hostname: rust
    build:
      context: ./.devcontainer
      dockerfile: Dockerfile.dev
      args:
        USER_UID: ${USER_UID:-1000}
    volumes:
      - ./:/workspace/api:cached
    init: true
    command: [ 'sleep', 'infinity' ]
